In [59]:
import numpy as np

In [60]:
an_array = np.array ([3,33,333]) #create a rank 1 array

print(type(an_array)) #the type of an nd arry is:

<class 'numpy.ndarray'>


In [61]:
print(an_array.shape)

(3,)


In [62]:
print(an_array[0], an_array[1],an_array[2])

3 33 333


In [63]:
an_array[0]=888
print (an_array)

[888  33 333]


In [64]:
another =np.array([[11,12,13] ,[21,22,23]])
print(another)
print("the shape is 2 rows , 3 columns",another.shape)
print("Accseing elements[0,0] ,[0,1] and [1,0] of the ndarray :"),another[0,0], " ," ,another[0,1]," ," ,another[1,0]

[[11 12 13]
 [21 22 23]]
the shape is 2 rows , 3 columns (2, 3)
Accseing elements[0,0] ,[0,1] and [1,0] of the ndarray :


(None, 11, ' ,', 12, ' ,', 21)

In [65]:
mt1 = np.zeros((2,2))
print(mt1)

[[0. 0.]
 [0. 0.]]


In [66]:
mt2 = np.full((2,2),1)
print(mt2)

[[1 1]
 [1 1]]


In [67]:
mt3 =np.eye(2,2)
print(mt3)

[[1. 0.]
 [0. 1.]]


In [68]:
mt4 = np.ones((2,1))
print(mt4)

[[1.]
 [1.]]


In [69]:
mt5 = np.random.random((2,2))
print(mt5)

[[0.10689417 0.17608617]
 [0.36887338 0.20623302]]


In [70]:
print(mt4.shape)
print()
print(mt4[0,0])

(2, 1)

1.0


In [71]:
an_array= np.array([[11,12,13,14] ,[21,22,23,24] ,[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [72]:
a_slice= an_array[0:2 ,1:3] #here we are slicing multiple row and column by giving range 0:2 row and 1:3 column
print(a_slice)

[[12 13]
 [22 23]]


In [73]:
print("before:" , an_array[0,1])
a_slice[0,0] = 1000        #single slice hence we use ,
print("After:" ,an_array[0,1])

before: 12
After: 1000


In [74]:
a_slice= an_array[1,:]
print(a_slice)

[21 22 23 24]


In [75]:
a_slice2= an_array[1:2 ,0:]
print(a_slice)

[21 22 23 24]


In [76]:
print(a_slice.shape)   

(4,)


In [77]:
print(a_slice2.shape)

(1, 4)


In [78]:
an_array = np.array([[11,12,13,14] ,[21,22,23,24] ,[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [79]:
row_rank1 =an_array[1,:]
print(row_rank1 ,row_rank1.shape)

[21 22 23 24] (4,)


In [80]:
row_rank2 = an_array[1:2,:]   #we are slicing from 1st 0,1,2,3  from 1st position to 2nd it will print till 1st position

In [81]:
print(row_rank2 , row_rank2.shape) 

[[21 22 23 24]] (1, 4)


In [82]:
print()
col_rank1 = an_array[:,1]  #out of 0,1,2,3  1st colum will be printed  
col_rank2=an_array[:,1:2]  #here we have given range 1:2 for column to print, it will only print 1 column and 2 col not printed  

print(col_rank1 , col_rank1.shape)
print()
print(col_rank2,col_rank2.shape)


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [83]:
an_array =np.array([[11,12,13] ,[21,22,23,] ,[31,32,33],[41,42,43]])
print('original Array :')
print(an_array)

original Array :
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [84]:
col_indices = np.array([0,1,2,0])    # we have given column indices 
print('\nCol indices picked:' ,col_indices)

row_indices =np.arange(4)#0,1,2,3   #we have given row indices  , 0th row 0th column in this way we will acess 
print('\nRows indices picked:',row_indices)


Col indices picked: [0 1 2 0]

Rows indices picked: [0 1 2 3]


In [85]:
#examine the paring of row_indices ND COL INDICES
for i,j in zip(row_indices,col_indices):
   print(i, " ," ,j)
''' for i in row_indices
for j in col_indices'''

0  , 0
1  , 1
2  , 2
3  , 0


' for i in row_indices\nfor j in col_indices'

In [86]:
#select one element form each row
print('values in the array at those indices:',an_array[row_indices ,col_indices])
#an_array[0,0],an_array[1,1],an_array [2,2],an_array[3,0]=an_array[row_indices ,col_indices]

values in the array at those indices: [11 22 33 41]


In [87]:
#change one element form each row using the indices selected
an_array[row_indices ,col_indices] +=100000

print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


In [88]:
#creat a 3 x 2 array 
an_array =np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [89]:
#create a filter ehich will be boolean values for wheather  each elements meets this condition
filter =(an_array>15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [90]:
#
print(an_array[filter])


[21 22 31 32]


In [91]:
an_array[an_array > 15]

array([21, 22, 31, 32])

In [92]:
an_array[an_array % 2 ==0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [93]:
ex1 = np.array([11,12]) 
print(ex1.dtype)

int32


In [94]:
ex2 =np.array([11.0,12.0])
print(ex2.dtype)

float64


In [95]:
ex3=np.array([11,21] ,dtype=np.int64)
print(ex3.dtype)

int64


In [96]:
ex4 =np.array([11.1,12.7],dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [97]:
ex5 =np.array([11,21],dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


# Arithmatic operation

In [98]:
import numpy as np

In [101]:
x = np.array([[111,112],[121,122]],dtype=np.int)
y  = np.array([[211.1,212.1],[221.1,222.1]],dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [102]:
#add
print(x+y)
print()
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [103]:
#subtract
print(x-y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [104]:
#multipy
print(x*y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [105]:
#divide
print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [106]:
#squre root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [107]:
#exponent(e**x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [108]:
#setup a random 2x 5 matix
arr = 10*np.random.randn(2,5) #random.random or random.randn or random.randint
print(arr)

[[ 27.15869546 -20.75862796   6.5476434    4.90037522  -5.2154873 ]
 [ -0.45416798  -6.16166883  -2.77991428  -2.38029073 -25.11311035]]


In [109]:
#compute the  mean for all elemnts
print(arr.mean())

-2.4256553341395337


In [110]:
#compute the mean by row
print(arr.mean(axis =1))

[ 2.52651976 -7.37783043]


In [111]:
#compute the mean by column
print(arr.mean(axis=0))

[ 13.35226374 -13.4601484    1.88386456   1.26004224 -15.16429882]


In [112]:
#sum all the elements
print(arr.sum())

-24.25655334139534


In [113]:
#compute the medians
print(np.median(arr,axis =1))

[ 4.90037522 -2.77991428]


In [114]:
#create q 10 elements array ofrandoms
unsorted =np.random.randn(10)

print(unsorted)

[-1.50068287  0.95351491  0.19651579 -0.59423224 -1.23733685  1.16057564
  0.88409714  0.42987335 -0.64242185  0.59292528]


In [115]:
#creat copy and sort
sorted =np.array(unsorted)
sorted.sort()#it will arrange values in ascending order ie sorting


print(sorted)
print()
print(unsorted)

[-1.50068287 -1.23733685 -0.64242185 -0.59423224  0.19651579  0.42987335
  0.59292528  0.88409714  0.95351491  1.16057564]

[-1.50068287  0.95351491  0.19651579 -0.59423224 -1.23733685  1.16057564
  0.88409714  0.42987335 -0.64242185  0.59292528]


In [116]:
#inpalce sorting
unsorted.sort()

print(unsorted)

[-1.50068287 -1.23733685 -0.64242185 -0.59423224  0.19651579  0.42987335
  0.59292528  0.88409714  0.95351491  1.16057564]


In [117]:
#finding unique elements
array =np.array([1,2,1,4,2,1,4,2])
print(np.unique(array)) 

[1 2 4]


In [118]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [119]:
##### print(np.intersect1d(s1,s2)) #COMMON VALUES BETN S1 AND S2

In [120]:
print(np.union1d(s1,s2))  #

['bulb' 'chair' 'desk' 'lamp']


In [121]:
print(np.setdiff1d(s1,s2))# element in  s1  that are not in s2

['desk']


In [122]:
print(np.in1d(s1,s2))#elemet of s1 is also in s2  

[False  True  True]


In [123]:
start= np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [124]:
add_rows = np.array([1,0,2])
print(add_rows)

[1 0 2]


In [125]:
y= start + add_rows 
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [126]:
#create  an ndarray which is 4x1 to broadcast across column 
add_cols =np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [127]:
#add to each column of start using broadcasting
y =start +add_cols      #here we have added vaules in start matrix 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [128]:
#this will just broadcast in both dimensions
add_scalar = np.array([1])   #here we have added 1 to  above start matix 
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [129]:
#creat out 3 x 4 matrix 
arrA =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [130]:
arrB =[0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [131]:
#add the two together using broadcsting
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


In [132]:
from numpy import arange
from timeit import Timer

size = 1000000
timeits =1000

In [133]:
#creat th ndarray  with values 0,1,2,.....,size-1
nd_array =arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [134]:
#timer expects the operation as a parameter,
#here we pass nd_array.sum
timer_numpy =Timer("nd_array.sum()" ,"from __main__ import nd_array")

print("Time taken by numpy ndarray :%f second" %
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray :0.001032 second


In [135]:
#creat the list with values 0,1,2...,size-1
a_list = list(range(size))
print(type(a_list))

<class 'list'>


In [136]:
#timer expects the operation as a parameter ,here we pass sum(a_list)
timer_list = Timer("sum(a_list)" , "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))


Time taken by list:  0.048138 seconds


In [137]:
import numpy  as np
x=np.array([23.23,24.24])

In [138]:
np.save('an_array',x) #saves the values in X to an_array

In [139]:
np.load('an_array.npy')  #we have loaded the same array that we have saved 

array([23.23, 24.24])

In [140]:
np.savetxt('array.txt',X=x ,delimiter=',')

In [141]:
np.savetxt('array.txt' ,X=x,delimiter=',')#save function will start your file in text format
np.loadtxt('array.txt', delimiter=',')#delimiter and sep are same which is seprated by comma 

array([23.23, 24.24])

In [142]:
#determine the dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d,y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [143]:
#determine the inner product of two vector
a1d = np.array([9,9])
b1d = np.array([10,10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d,b1d))

180

180


In [144]:
#sum element in the array
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1)) #add all member

66


In [145]:
print(np.sum(ex1,axis=0)) #for columwise sum

[32 34]


In [146]:
print(np.sum(ex1,axis=1)) #for rowwise sum

[23 43]


In [147]:
#random array     we are giving random elements from x and y and finding maximium value 
x =np.random.randn(8)
x

array([-1.16466543,  0.84398725,  0.7524632 ,  1.05698063, -0.40661861,
        0.69999632,  0.25076918, -2.05329667])

In [148]:
#another random array
y=np.random.randn(8)
y

array([ 0.23355718, -0.33826161, -0.40264743, -0.44719088, -1.65886527,
       -0.75196572,  0.08671739,  0.63059924])

In [149]:
#return element wise maximum between two arrays
import numpy as np
#x=np.random.randn(8)
#y=np.random.randn(8)
np.maximum(x,y)

array([ 0.23355718,  0.84398725,  0.7524632 ,  1.05698063, -0.40661861,
        0.69999632,  0.25076918,  0.63059924])

In [150]:
#grab values from 0 through 19 in an array 
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [151]:
#reshape to be a 4 x 5 matrix 
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [152]:
#transpose 
ex1 = np.array([[11,12],[21,22]])
print(ex1)
ex1.T

[[11 12]
 [21 22]]


array([[11, 21],
       [12, 22]])

In [153]:
x_1 = np.array([1,2,3,4,5])
y_1 = np.array([11,22,33,44,55])
#where we have true value in filter it  will print x_1 value and for false y_1 value
#this is the working of where function
filter = np.array([True,False,True,False,True ])

In [154]:
out = np.where(filter,x_1,y_1)
print(out)

[ 1 22  3 44  5]


In [155]:
mat = np.random.rand(5,5)
mat

array([[0.26523213, 0.31848698, 0.8649421 , 0.07366513, 0.98798163],
       [0.03255354, 0.01666666, 0.90607237, 0.4106051 , 0.21207711],
       [0.82091329, 0.89093598, 0.74449148, 0.74922179, 0.77768672],
       [0.86302106, 0.2831827 , 0.0389289 , 0.76622969, 0.3302093 ],
       [0.79563636, 0.71508641, 0.53498445, 0.74925805, 0.16073367]])

In [156]:
np.where( mat > 0.5 , 1000, -1 )
#if mat>0.5
       # replace(1000
     #else :
        # replace(-1) 

array([[  -1,   -1, 1000,   -1, 1000],
       [  -1,   -1, 1000,   -1,   -1],
       [1000, 1000, 1000, 1000, 1000],
       [1000,   -1,   -1, 1000,   -1],
       [1000, 1000, 1000, 1000,   -1]])

In [157]:
True,False,True,True,False])arr_bools =np.array([

In [158]:
arr_bools.any() #is any value in array is true then it will print ture 

True

In [159]:
arr_bools.all() # if all values are  True only then print True

False

In [160]:
import numpy as np
Y = np.random.normal(size = (1,5))
print(Y)

[[ 0.45638083  0.59228864  1.10394346  1.54772522 -1.07166959]]


In [161]:
Z= np.random.randint(low=2,high=50,size=4)#int interger values
print(Z) #low for lower limits and high for higher kimits 

[41 46 13 22]


In [162]:
np.random.permutation(Z) #return a new ordering of elemnts in Z 

array([13, 41, 46, 22])

In [163]:
np.random.uniform(size=4) #uniform distribution

array([0.33621523, 0.07125023, 0.48274151, 0.78245751])

In [164]:
np.random.normal(size=4) #normal distribution

array([-0.85125733,  0.08064977, -0.23030675, -0.94290374])

In [165]:
K= np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M =np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[49 31]
 [ 6 43]]

[[29  5]
 [24  3]]


In [166]:
np.vstack((K,M)) #joint vertically 

array([[49, 31],
       [ 6, 43],
       [29,  5],
       [24,  3]])

In [167]:
np.hstack((K,M))#join horizontally

array([[49, 31, 29,  5],
       [ 6, 43, 24,  3]])

In [168]:
np.concatenate([K,M],axis=0) #rows match

array([[49, 31],
       [ 6, 43],
       [29,  5],
       [24,  3]])

In [169]:
np.concatenate([K,M.T] , axis=1) #M traspose column  match 

array([[49, 31, 29, 24],
       [ 6, 43,  5,  3]])